language: php
dist: trusty
sudo: required

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  global:
   - SECP256K1_COMMIT=cd329dbc3eaf096ae007e807b86b6f5947621ee3
   - DOCKER_CACHE_DIR=/home/travis/docker

cache:
  directories:
    - ${DOCKER_CACHE_DIR}

matrix:
  exclude:
    - php: 7.0

  include:
    - php: 7.0
      env: COVERAGE_TARGET=95 COVERAGE=true COVERAGE_PREFIX_FUNCTIONS=zif_,zm_,secp256k1_

before_install:
  - sudo apt-get install -qq libssl-dev
  - if [ "${COVERAGE}" = "true" ]; then ./travis/docker-load-cache.sh secp256k1build || echo "failed"; fi

install:
  - |
      git clone https://github.com/bitcoin-core/secp256k1.git libsecp256k1        \
      && cd libsecp256k1 && git checkout $SECP256K1_COMMIT                        \
      && ./autogen.sh                                                             \
      && ./configure --enable-tests=no --enable-benchmark=no                      \
             --enable-experimental --enable-module-{ecdh,recovery}                \
      && make -j$(nproc) && sudo make install && cd ..
  - |
      cd secp256k1 && phpize                                                      \
      && ./configure && make -j$(nproc) && sudo make install                      \
      && cd ..
  - composer update

before_script:
  - |
      if [ "${COVERAGE}" = "true" ]; then \
          cd travis/phpqa/ && docker build -t secp256k1build . && cd ../.. && \
          ./travis/docker-save-cache.sh secp256k1build
      fi

script:
  - cd secp256k1/ && REPORT_EXIT_STATUS=1 make test || exit 1 && cd ..
  - php -dextension=secp256k1.so vendor/phpunit/phpunit/phpunit tests/ || exit 1
  - travis/run_coverage_test.sh || exit 1
  - travis/validate_examples.sh || exit 1
