language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - nightly

matrix:
    allow_failures:
        - php: nightly

before_install:
#    - sudo apt-get update -qq
    - sudo apt-get install -qq libssl-dev

install:
    - |
        git clone git://github.com/bitcoin/secp256k1.git libsecp256k1 \
        && cd libsecp256k1 \
        && ./autogen.sh && ./configure --enable-experimental --enable-module-{ecdh,recovery} && make && sudo make install \
        && cd ..
    - |
        cd secp256k1 \
        && phpize && ./configure && make && sudo make install \
        && cd ..
    - composer update

before_script:
    - php-config || true
    - phpenv rehash
    - phpenv version-name

script:
    - |
        cd libsecp256k1 \
        && ./tests \
        && cd ..
    - php -dextension=secp256k1.so vendor/phpunit/phpunit/phpunit tests/
