language: php
dist: trusty
sudo: required

env:
  global:
   - SECP256K1_COMMIT=fa3301713549d118e57ebe6551d062903ddd6b63
   - DOCKER_CACHE_DIR=/home/travis/docker
   - CC_FOR_BUILD=gcc

cache:
  directories:
    - ${DOCKER_CACHE_DIR}

matrix:
  include:
    - php: 7.3
      env: COVERAGE=true PHPQA_PHP_VERSION=7.3.7
      before_script: cd travis/phpqa/ && ./build_container.sh && cd ../.. && \
                     ./travis/docker-save-cache.sh secp256k1-{$PHPQA_PHP_VERSION}
    - php: 7.3
      env: CC_FOR_BUILD=clang
    - php: 7.2
    - php: 7.1
    - php: 7.0

before_install:
  - sudo apt-get install -qq libssl-dev
  - if [ "${COVERAGE}" = "true" ]; then ./travis/docker-load-cache.sh secp256k1-${PHPQA_PHP_VERSION} || echo "failed"; fi

install:
  - |
      git clone https://github.com/bitcoin-core/secp256k1.git libsecp256k1        \
      && cd libsecp256k1 && git checkout $SECP256K1_COMMIT                        \
      && ./autogen.sh                                                             \
      && ./configure --enable-tests=no --enable-benchmark=no                      \
             --enable-experimental --enable-module-{ecdh,recovery}                \
             CC=${CC_FOR_BUILD}                                                   \
      && make -j$(nproc) && sudo make install && cd ..
  - |
      cd secp256k1 && phpize                                                      \
      && ./configure CC=${CC_FOR_BUILD}                                           \
      && make -j$(nproc) && sudo make install                                     \
      && cd ..
  - composer update

script:
  - travis/verify_stubs.sh
  - cd secp256k1/ && REPORT_EXIT_STATUS=1 make test TESTS="-m" || (find tests/*.log -type f -exec cat {} + ; exit 1) && cd ..
  - travis/run_coverage_test.sh || exit 1
  - travis/validate_examples.sh || exit 1

after_script:
    - bash <(curl -s https://codecov.io/bash)
